### ISSUE TITLE
Can't install distance rasters on ARM / Mac M1 because of Fiona build error

### ISSUE THREAD

**Issue by rbavery** [developmentseed/slickformer#14]
Moving the dependency to the environment.yaml for now so that environment-m1.yaml can build.

**Comment by weiji14** [comment]
Maybe related to https://github.com/Toblerity/Fiona/issues/1250? The issue there suggests using `pip>=22.3` or using `fiona==1.8.22`.

We could also make a conda-forge package for [distancerasters](https://github.com/sgoodm/python-distance-rasters) if that would make things easier.

**Comment by sgillies** [comment]
@rbavery @weiji14 Do upgrade pip, it's always a good idea to use the latest pip. Don't downgrade fiona.

**Comment by rbavery** [comment]
thanks @sgillies for the tip. this probably isn't an issue anymore.
