### ISSUE TITLE
graphviz doesn't work in container

### ISSUE THREAD

**Issue by rbavery** [developmentseed/slickformer#9]
I updated the container to add xdg-open but when I run to_graph:

```
/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: elinks: not found
/usr/bin/xdg-open: 869: links: not found
/usr/bin/xdg-open: 869: lynx: not found
/usr/bin/xdg-open: 869: w3m: not found
xdg-open: no method available for opening 'Digraph.gv.pdf'
```

not finding a lot of hits on how to solve this so moving on and not using to_graph for now to inspect datapipe

**Comment by weiji14** [comment]
Using [`to_graph`](https://pytorch.org/data/0.6/generated/torchdata.datapipes.utils.to_graph.html) works for me in JupyterLab from the docker container:

![image](https://user-images.githubusercontent.com/23487320/236114091-2d843839-96cb-4cec-8747-79e3220de1f2.png)

Code:

```python
import torchdata

dp = torchdata.datapipes.iter.IterableWrapper(iterable=range(10))
torchdata.datapipes.utils.to_graph(dp)
```
Are you running this in the bash shell?

**Comment by rbavery** [comment]
Sorry stale issue, this is fixed now!
